### ISSUE TITLE
dataset_tools

### ISSUE THREAD

**Issue by aqzwy** [arthurcgusmao/SFE#1]
where i  can get the  dataset_tools

**Comment by arthurcgusmao** [comment]
Hi @aqzwy , thanks for reaching out. The dataset_tools is a [module within the XKE library](https://github.com/arthurcgusmao/XKE/blob/xke-master/tools/dataset_tools.py).

Please, keep in mind that I have not performed all necessary tests in this implementation of SFE to see if it is correctly working. For the canonical implementation, please check [Gardner's repo](https://github.com/matt-gardner/pra).

If you are trying to use SFE to extract features for XKE, you will want to use [my fork of Gardner's code](https://github.com/arthurcgusmao/pra) which breaks code execution in order to prevent RAM explosion.

Also, I would appreciate if you open pull requests in case you improve this code. I may come back to work on it again within the next months.
